language: node_js
node_js:
  - "13"
before_install:
  - npm i -g npm@^6.14.5
before_script:
  - rm -rf package-lock.json node_modules/
  - npm install .
  - npm run build default
install:
  - echo "passthrough"
script: gulp
